
api_calculate:
    path: /api/calculate
    controller: App\Controller\CreditController::calculate
    methods: GET

api_list_schedules:
    path: /api/schedules
    controller: App\Controller\CreditController::listSchedules
    methods: GET

api_exclude_schedule:
    path: /api/exclude/{id}
    controller: App\Controller\CreditController::excludeSchedule
    methods: DELETE